version: '3'

services:
    db:
      image: postgres:${POSTGRES_TAG}
      volumes:
        - ./docker/db/init:/docker-entrypoint-initdb.d
        - ${DATA_PATH_HOST}:/var/lib/postgresql/data
      ports:
        - "${POSTGRES_PORT}:5432"
      environment:
        - POSTGRES_DEV_DB=${POSTGRES_DEV_DB}
        - POSTGRES_TEST_DB=${POSTGRES_TEST_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}